name: Java CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      # ✅ Build Docker Image (ONLY ONE)
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/qr-wallet-app:latest .

      # ✅ Login Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # ✅ Push Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/qr-wallet-app:latest